# Generated by Django 6.0.4 on 2026-05-05 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='device',
        ),
        migrations.RemoveField(
            model_name='device',
            name='department',
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='deviceassignment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='checked_by',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='condition_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='device',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='device',
            name='warranty_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='assigned_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.branch'),
        ),
        migrations.AlterField(
            model_name='device',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.employee'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned'), ('PENDING_RETURN', 'Pending Return'), ('IN_REPAIR', 'In Repair'), ('REPAIRED', 'Repaired'), ('MISSING', 'Missing'), ('RETIRED', 'Retired')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='deviceassignment',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.department'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('VERIFIED', 'Verified'), ('MISSING', 'Missing')], max_length=10),
        ),
        migrations.AlterField(
            model_name='inventorysession',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.branch'),
        ),
        migrations.AlterField(
            model_name='repairlog',
            name='repair_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.repairrequest'),
        ),
        migrations.AlterField(
            model_name='repairrequest',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.device'),
        ),
        migrations.AlterField(
            model_name='repairrequest',
            name='priority',
            field=models.CharField(default='NORMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='repairrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('HEAD_OFFICE', 'Head Office'), ('BRANCH_MANAGER', 'Branch Manager'), ('TECHNICIAN', 'Technician'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
