# Generated by Django 6.0.3 on 2026-05-11 09:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_device_completed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('VERIFIED', 'Verified'), ('MISSING', 'Missing'), ('EXTRA', 'Extra'), ('IN_REPAIR', 'In Repair'), ('RETURNED_HEAD_OFFICE', 'Returned to Head Office')], max_length=30),
        ),
        migrations.AlterField(
            model_name='repairlog',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
