# Generated by Django 6.0.3 on 2026-05-22 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_soft_delete_location_decommission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='department',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='device',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='device',
            name='location_type',
            field=models.CharField(choices=[('HEAD_OFFICE', 'Head Office'), ('BRANCH', 'Branch'), ('EMPLOYEE', 'Employee'), ('TECHNICIAN', 'Head Office / Technician')], default='HEAD_OFFICE', max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned'), ('PENDING_RETURN', 'Pending Return'), ('IN_REPAIR', 'In Repair'), ('COMPLETED', 'Completed'), ('REPAIRED', 'Repaired'), ('MISSING', 'Missing'), ('RETIRED', 'Retired'), ('DECOMMISSIONED', 'Decommissioned')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
