# Generated by Django 6.0.4 on 2026-05-24 11:16

import django.db.models.deletion
from django.db import migrations, models


def seed_access_control(apps, schema_editor):
    Module = apps.get_model('App', 'Module')
    Permission = apps.get_model('App', 'Permission')
    Role = apps.get_model('App', 'Role')
    RolePermission = apps.get_model('App', 'RolePermission')
    User = apps.get_model('App', 'User')

    from App.access_control import MODULE_DEFINITIONS, PERMISSION_DEFINITIONS, DEFAULT_ROLE_PERMISSIONS, SYSTEM_ROLE_LABELS

    permission_by_codename = {}
    for key, name, description in MODULE_DEFINITIONS:
        module, _ = Module.objects.get_or_create(
            key=key,
            defaults={"module_name": name, "description": description},
        )
        if module.module_name != name or module.description != description:
            module.module_name = name
            module.description = description
            module.save(update_fields=["module_name", "description"])
        for codename, permission_name in PERMISSION_DEFINITIONS.get(key, []):
            permission, _ = Permission.objects.get_or_create(
                codename=codename,
                defaults={"module": module, "permission_name": permission_name},
            )
            permission_by_codename[codename] = permission

    all_permissions = list(permission_by_codename.values())
    for code, label in SYSTEM_ROLE_LABELS.items():
        role, _ = Role.objects.get_or_create(
            code=code,
            defaults={
                "name": label,
                "description": "Built-in system role.",
                "is_system": True,
            },
        )
        role.name = label
        role.is_system = True
        role.save(update_fields=["name", "is_system"])
        configured_permissions = DEFAULT_ROLE_PERMISSIONS.get(code, [])
        permissions = all_permissions if configured_permissions == "__all__" else [
            permission_by_codename[codename]
            for codename in configured_permissions
            if codename in permission_by_codename
        ]
        for permission in permissions:
            RolePermission.objects.get_or_create(role=role, permission=permission)

    for user in User.objects.filter(dynamic_role__isnull=True):
        role = Role.objects.filter(code=user.role).first()
        if role:
            user.dynamic_role = role
            user.save(update_fields=["dynamic_role"])


def unseed_access_control(apps, schema_editor):
    Role = apps.get_model('App', 'Role')
    Module = apps.get_model('App', 'Module')
    Role.objects.filter(is_system=True).delete()
    Module.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_alter_branch_deleted_by_alter_department_deleted_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('module_name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['module_name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('HEAD_OFFICE', 'Head Office'), ('BRANCH_MANAGER', 'Branch Manager'), ('TECHNICIAN', 'Technician'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=30),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.SlugField(max_length=100, unique=True)),
                ('permission_name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='App.module')),
            ],
            options={
                'ordering': ['module__module_name', 'permission_name'],
                'unique_together': {('module', 'permission_name')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='dynamic_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='App.role'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='App.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='App.role')),
            ],
            options={
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', through='App.RolePermission', to='App.permission'),
        ),
        migrations.RunPython(seed_access_control, unseed_access_control),
    ]
