from django.urls import path
from .views import (
    home_view,
    login_view,
    logout_view,
    dashboard_redirect,
    profile_details,
    account_settings,
    first_login_password_change,
    head_office_dashboard,
    head_office_employees,
    head_office_branches,
    head_office_departments,
    head_office_devices,
    head_office_assignments,
    head_office_repairs,
    head_office_audit_device,
    head_office_inventory,
    head_office_inventory_detail,
    head_office_reports,
    head_office_audit_logs,
    branch_manager_dashboard,
    branch_devices,
    branch_employees,
    branch_inventory_verification,
    branch_reports,
    employee_dashboard,
    employee_my_devices,
    employee_request_repair,
    employee_repair_requests,
    technician_dashboard,
    technician_repairs,
    technician_in_progress_repairs,
    technician_completed_repairs,
    technician_device_lookup,
    technician_repair_history,
)

urlpatterns = [
    path("", home_view, name="home"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("dashboard/", dashboard_redirect, name="dashboard_redirect"),
    path("profile/", profile_details, name="profile_details"),
    path("account-settings/", account_settings, name="account_settings"),
    path("change-default-password/", first_login_password_change, name="first_login_password_change"),
    
    # Head Office Routes
    path("dashboard/head-office/", head_office_dashboard, name="head_office_dashboard"),
    path("head-office/employees/", head_office_employees, name="head_office_employees"),
    path("head-office/branches/", head_office_branches, name="head_office_branches"),
    path("head-office/departments/", head_office_departments, name="head_office_departments"),
    path("head-office/devices/", head_office_devices, name="head_office_devices"),
    path("head-office/assignments/", head_office_assignments, name="head_office_assignments"),
    path("head-office/repairs/", head_office_repairs, name="head_office_repairs"),
    path("head-office/audit-device/", head_office_audit_device, name="head_office_audit_device"),
    path("head-office/inventory/", head_office_inventory, name="head_office_inventory"),
    path("head-office/inventory/<int:session_id>/", head_office_inventory_detail, name="head_office_inventory_detail"),
    path("head-office/reports/", head_office_reports, name="head_office_reports"),
    path("head-office/audit-logs/", head_office_audit_logs, name="head_office_audit_logs"),
    
    # Other Dashboards
    path("dashboard/branch/", branch_manager_dashboard, name="branch_manager_dashboard"),
    path("branch/devices/", branch_devices, name="branch_devices"),
    path("branch/employees/", branch_employees, name="branch_employees"),
    path("branch/inventory/", branch_inventory_verification, name="branch_inventory_verification"),
    path("branch/reports/", branch_reports, name="branch_reports"),
    path("dashboard/employee/", employee_dashboard, name="employee_dashboard"),
    path("employee/my-devices/", employee_my_devices, name="employee_my_devices"),
    path("employee/request-repair/", employee_request_repair, name="employee_request_repair"),
    path("employee/repair-requests/", employee_repair_requests, name="employee_repair_requests"),
    path("dashboard/technician/", technician_dashboard, name="technician_dashboard"),
    path("technician/repairs/", technician_repairs, name="technician_repairs"),
    path("technician/in-progress/", technician_in_progress_repairs, name="technician_in_progress_repairs"),
    path("technician/completed/", technician_completed_repairs, name="technician_completed_repairs"),
    path("technician/device-lookup/", technician_device_lookup, name="technician_device_lookup"),
    path("technician/repair-history/", technician_repair_history, name="technician_repair_history"),
]
